BEGIN TRANSACTION

USE [GD1C2023]
GO

ALTER TABLE [BASE_DE_GATOS_2].[LOCALES] DROP CONSTRAINT [FK_LOCAL_CATEGORIA_LOCALES]
GO

ALTER TABLE [BASE_DE_GATOS_2].[LOCAL_CATEGORIAS] DROP CONSTRAINT [FK_LOCAL_TIPO_LOCAL_CATEGORIAS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[LOCAL_PRODUCTO] DROP CONSTRAINT [FK_LP_LOCAL_LOCAL_PRODUCTO]
GO

ALTER TABLE [BASE_DE_GATOS_2].[LOCAL_PRODUCTO] DROP CONSTRAINT [FK_LP_PRODUCTO_LOCAL_PRODUCTO]
GO

ALTER TABLE [BASE_DE_GATOS_2].[LOCAL_PRODUCTO_PEDIDO] DROP CONSTRAINT [FK_LPC_LOCAL_PRODUCTO_LOCAL_PRODUCTO_PEDIDO]
GO

ALTER TABLE [BASE_DE_GATOS_2].[LOCAL_PRODUCTO_PEDIDO] DROP CONSTRAINT [FK_LPC_PEDIDO_LOCAL_PRODUCTO_PEDIDO]
GO

ALTER TABLE [BASE_DE_GATOS_2].[HORARIOS] DROP CONSTRAINT [FK_HORARIO_DIA_HORARIOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[HORARIOS] DROP CONSTRAINT [FK_LOCAL_HORARIOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[LOCALIDADES] DROP CONSTRAINT [FK_LOCALIDAD_PROVINCIA_LOCALIDADES]
GO

ALTER TABLE [BASE_DE_GATOS_2].[DIRECCION] DROP CONSTRAINT [FK_LOCALIDAD_DIRECCION]
GO

ALTER TABLE [BASE_DE_GATOS_2].[REPARTIDORES] DROP CONSTRAINT [FK_REPARTIDOR_LOCALIDAD_ACTIVA_REPARTIDORES]
GO

ALTER TABLE [BASE_DE_GATOS_2].[REPARTIDORES] DROP CONSTRAINT [FK_REPARTIDOR_TIPO_MOVILIDAD_REPARTIDORES]
GO

ALTER TABLE [BASE_DE_GATOS_2].[ENVIO_PEDIDO] DROP CONSTRAINT [FK_EP_REPARTIDOR_ENVIO_PEDIDO]
GO

ALTER TABLE [BASE_DE_GATOS_2].[ENVIO_PEDIDO] DROP CONSTRAINT [FK_EP_DIRECCION_ENVIO_PEDIDO]
GO

ALTER TABLE [BASE_DE_GATOS_2].[MEDIOS_DE_PAGO] DROP CONSTRAINT [FK_TIPO_MEDIO_PAGO_MEDIO_PAGO]
GO

ALTER TABLE [BASE_DE_GATOS_2].[MEDIOS_DE_PAGO] DROP CONSTRAINT [FK_TIPO_MARCAS_TARJETA_MEDIO_PAGO]
GO

ALTER TABLE [BASE_DE_GATOS_2].[MEDIOS_DE_PAGO] DROP CONSTRAINT [FK_TIPO_USUARIOS_MEDIO_PAGO]
GO

ALTER TABLE [BASE_DE_GATOS_2].[USUARIOS] DROP CONSTRAINT [FK_USUARIOS_DIRECCION]
GO

ALTER TABLE [BASE_DE_GATOS_2].[DIRECCION_USUARIO] DROP CONSTRAINT [FK_USUARIOS_DIRECCION_USUARIO]
GO

ALTER TABLE [BASE_DE_GATOS_2].[DIRECCION_USUARIO] DROP CONSTRAINT [FK_DIRECCION_DIRECCION_USUARIO]
GO

ALTER TABLE [BASE_DE_GATOS_2].[PEDIDOS] DROP CONSTRAINT [FK_ESTADO_PEDIDO_PEDIDOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[PEDIDOS] DROP CONSTRAINT [FK_USUARIOS_PEDIDOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[PEDIDOS] DROP CONSTRAINT [FK_LOCALES_PEDIDOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[PEDIDOS] DROP CONSTRAINT [FK_MEDIOS_DE_PAGO_PEDIDOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[RECLAMOS] DROP CONSTRAINT [FK_TIPO_RECLAMO_RECLAMOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[RECLAMOS] DROP CONSTRAINT [FK_ESTADO_RECLAMO_RECLAMOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[RECLAMOS] DROP CONSTRAINT [FK_USUARIOS_RECLAMOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[RECLAMOS] DROP CONSTRAINT [FK_PEDIDOS_RECLAMOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[RECLAMOS] DROP CONSTRAINT [FK_OPERADORES_RECLAMOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[ENVIO_MENSAJERIA] DROP CONSTRAINT [FK_EM_ESTADO_EM]
GO

ALTER TABLE [BASE_DE_GATOS_2].[ENVIO_MENSAJERIA] DROP CONSTRAINT [FK_EM_USUARIOS]
GO

ALTER TABLE [BASE_DE_GATOS_2].[ENVIO_MENSAJERIA] DROP CONSTRAINT [FK_EM_TIPO_PAQUETES]
GO

ALTER TABLE [BASE_DE_GATOS_2].[ENVIO_MENSAJERIA] DROP CONSTRAINT [FK_EM_REPARTIDORES]
GO

ALTER TABLE [BASE_DE_GATOS_2].[ENVIO_MENSAJERIA] DROP CONSTRAINT [FK_EM_MEDIOS_DE_PAGO]
GO


DROP TABLE [BASE_DE_GATOS_2].[LOCALES]
GO

DROP TABLE [BASE_DE_GATOS_2].[LOCAL_CATEGORIAS]
GO

DROP TABLE [BASE_DE_GATOS_2].[LOCAL_PRODUCTO]
GO

DROP TABLE [BASE_DE_GATOS_2].[LOCAL_PRODUCTO_PEDIDO]
GO

DROP TABLE [BASE_DE_GATOS_2].[HORARIOS]
GO

DROP TABLE [BASE_DE_GATOS_2].[LOCALIDADES]
GO

DROP TABLE [BASE_DE_GATOS_2].[DIRECCION]
GO

DROP TABLE [BASE_DE_GATOS_2].[REPARTIDORES]
GO

DROP TABLE [BASE_DE_GATOS_2].[ENVIO_PEDIDO]
GO

DROP TABLE [BASE_DE_GATOS_2].[MEDIOS_DE_PAGO]
GO

DROP TABLE [BASE_DE_GATOS_2].[USUARIOS]
GO

DROP TABLE [BASE_DE_GATOS_2].[DIRECCION_USUARIO]
GO

DROP TABLE [BASE_DE_GATOS_2].[PEDIDOS]
GO

DROP TABLE [BASE_DE_GATOS_2].[RECLAMOS]
GO

DROP TABLE [BASE_DE_GATOS_2].[ENVIO_MENSAJERIA]
GO

DROP TABLE [BASE_DE_GATOS_2].[ESTADO_ENVIO_MENSAJERIA]
GO

DROP TABLE [BASE_DE_GATOS_2].[ESTADO_PEDIDO]
GO

DROP TABLE [BASE_DE_GATOS_2].[ESTADO_RECLAMO]
GO

DROP TABLE [BASE_DE_GATOS_2].[HORARIO_DIAS]
GO

DROP TABLE [BASE_DE_GATOS_2].[LOCAL_TIPOS]
GO

DROP TABLE [BASE_DE_GATOS_2].[MARCAS_TARJETA]
GO

DROP TABLE [BASE_DE_GATOS_2].[MOVILIDAD]
GO

DROP TABLE [BASE_DE_GATOS_2].[OPERADORES]
GO

DROP TABLE [BASE_DE_GATOS_2].[PRODUCTOS]
GO

DROP TABLE [BASE_DE_GATOS_2].[PROVINCIAS]
GO

DROP TABLE [BASE_DE_GATOS_2].[SOLUCION_RECLAMO]
GO

DROP TABLE [BASE_DE_GATOS_2].[TIPO_MEDIO_DE_PAGO]
GO

DROP TABLE [BASE_DE_GATOS_2].[TIPO_PAQUETES]
GO

DROP TABLE [BASE_DE_GATOS_2].[TIPO_RECLAMO]
GO

DROP SCHEMA BASE_DE_GATOS_2

COMMIT